In [ ]:
from zipfile import ZipFile
from kaggle.api.kaggle_api_extended import KaggleApi
from functools import reduce

from ast import literal_eval

In [5]:
# Kaggle API authentication
api = KaggleApi()
api.authenticate()

Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /Users/quentinmowat-amiet/.kaggle/kaggle.json'

In [6]:
# Download stock mkt indicators datasets
"""This dataset has around 64 features which include features extracted 
from OHLC, other index prices such as QQQ(Nasdaq-100 ETF) & S&P 500, 
technical indicators such as Bollinger bands, 
EMA(Exponential Moving Averages), Stochastic %K oscillator, RSI, etc."""
api.dataset_download_files('nikhilkohli/us-stock-market-data-60-extracted-features', 'datasets/stock_mkt_indicators/')

In [7]:
# Unzip datasets file
with ZipFile(
        'datasets/stock_mkt_indicators/us-stock-market-data-60-extracted-features.zip',
        'r') as zipObj:
    # Extract all the contents of zip file in current directory
    zipObj.extractall('datasets/stock_mkt_indicators/')

In [8]:
# Import datasets
aapl = pd.read_csv('datasets/stock_mkt_indicators/AAPL.csv')
amzn = pd.read_csv('datasets/stock_mkt_indicators/AMZN.csv')
fb = pd.read_csv('datasets/stock_mkt_indicators/FB.csv')
ge = pd.read_csv('datasets/stock_mkt_indicators/GE.csv')
googl = pd.read_csv('datasets/stock_mkt_indicators/GOOGL.csv')
gs = pd.read_csv('datasets/stock_mkt_indicators/GS.csv')
ibm = pd.read_csv('datasets/stock_mkt_indicators/IBM.csv')
jpm = pd.read_csv('datasets/stock_mkt_indicators/JPM.csv')
msft = pd.read_csv('datasets/stock_mkt_indicators/MSFT.csv')
tsla = pd.read_csv('datasets/stock_mkt_indicators/TSLA.csv')

In [9]:
# Stock name column
aapl['stock'] = "Apple"
amzn['stock'] = "Amazon"
fb['stock'] = "Facebook"
ge['stock'] = "General Electric"
googl['stock'] = "Google"
gs['stock'] = "Goldman Sachs"
ibm['stock'] = "IBM"
jpm['stock'] = "JPMorgan Chase"
msft['stock'] = "Microsoft"
tsla['stock'] = "Tesla"

# Exploratory Data Analysis

In [11]:
# 
aapl_corr_df = pd.DataFrame({'Apple':aapl.corr()['Close(t)']}).sort_values(by = 'Apple', axis = 0, ascending = False)
amzn_corr_df = pd.DataFrame({'Amazon':amzn.corr()['Close(t)']}).sort_values(by = 'Amazon', axis = 0, ascending = False)
fb_corr_df = pd.DataFrame({'Facebook':fb.corr()['Close(t)']}).sort_values(by = 'Facebook', axis = 0, ascending = False)
ge_corr_df = pd.DataFrame({'General Electric':ge.corr()['Close(t)']}).sort_values(by = 'General Electric', axis = 0, ascending = False)
googl_corr_df = pd.DataFrame({'Google':googl.corr()['Close(t)']}).sort_values(by = 'Google', axis = 0, ascending = False)
gs_corr_df = pd.DataFrame({'Goldman Sachs':gs.corr()['Close(t)']}).sort_values(by = 'Goldman Sachs', axis = 0, ascending = False)
ibm_corr_df = pd.DataFrame({'IBM':ibm.corr()['Close(t)']}).sort_values(by = 'IBM', axis = 0, ascending = False)
jpm_corr_df = pd.DataFrame({'JPMorgan Chase':jpm.corr()['Close(t)']}).sort_values(by = 'JPMorgan Chase', axis = 0, ascending = False)
msft_corr_df = pd.DataFrame({'Microsoft':msft.corr()['Close(t)']}).sort_values(by = 'Microsoft', axis = 0, ascending = False)
tsla_corr_df = pd.DataFrame({'Tesla':tsla.corr()['Close(t)']}).sort_values(by = 'Tesla', axis = 0, ascending = False)

In [12]:
# 
aapl_corr_df = aapl_corr_df[aapl_corr_df['Apple'] >= 0.75]
aapl_corr_df['Rank'] = aapl_corr_df['Apple'].rank(axis = 0, method = 'first')
aapl_corr_df.index.name = 'index'
amzn_corr_df = amzn_corr_df[amzn_corr_df['Amazon'] >= 0.75]
amzn_corr_df['Rank'] = amzn_corr_df['Amazon'].rank(axis = 0, method = 'first')
amzn_corr_df.index.name = 'index'
fb_corr_df = fb_corr_df[fb_corr_df['Facebook'] >= 0.75]
fb_corr_df['Rank'] = fb_corr_df['Facebook'].rank(axis = 0, method = 'first')
fb_corr_df.index.name = 'index'
ge_corr_df = ge_corr_df[ge_corr_df['General Electric'] >= 0.75]
ge_corr_df['Rank'] = ge_corr_df['General Electric'].rank(axis = 0, method = 'first')
ge_corr_df.index.name = 'index'
googl_corr_df = googl_corr_df[googl_corr_df['Google'] >= 0.75]
googl_corr_df['Rank'] = googl_corr_df['Google'].rank(axis = 0, method = 'first')
googl_corr_df.index.name = 'index'
gs_corr_df = gs_corr_df[gs_corr_df['Goldman Sachs'] >= 0.75]
gs_corr_df['Rank'] = gs_corr_df['Goldman Sachs'].rank(axis = 0, method = 'first')
gs_corr_df.index.name = 'index'
ibm_corr_df = ibm_corr_df[ibm_corr_df['IBM'] >= 0.75]
ibm_corr_df['Rank'] = ibm_corr_df['IBM'].rank(axis = 0, method = 'first')
ibm_corr_df.index.name = 'index'
jpm_corr_df = jpm_corr_df[jpm_corr_df['JPMorgan Chase'] >= 0.75]
jpm_corr_df['Rank'] = jpm_corr_df['JPMorgan Chase'].rank(axis = 0, method = 'first')
jpm_corr_df.index.name = 'index'
msft_corr_df = msft_corr_df[msft_corr_df['Microsoft'] >= 0.75]
msft_corr_df['Rank'] = msft_corr_df['Microsoft'].rank(axis = 0, method = 'first')
msft_corr_df.index.name = 'index'
tsla_corr_df = tsla_corr_df[tsla_corr_df['Tesla'] >= 0.75]
tsla_corr_df['Rank'] = tsla_corr_df['Tesla'].rank(axis = 0, method = 'first')
tsla_corr_df.index.name = 'index'

In [13]:
# 
df_rank_corr = pd.concat([aapl_corr_df, amzn_corr_df, fb_corr_df, ge_corr_df, googl_corr_df, gs_corr_df,
    ibm_corr_df, jpm_corr_df, msft_corr_df, tsla_corr_df]).groupby(['index']).sum()
df_rank_corr = pd.DataFrame(df_rank_corr['Rank']).sort_values(by = 'Rank', axis = 0, ascending = False).reset_index()
df_rank_corr

            index   Rank
0        Close(t)  322.0
1             Low  308.0
2            High  306.0
3            Open  287.0
4           EMA20  281.0
5           EMA50  271.0
6          EMA100  261.0
7           EMA10  251.0
8          EMA200  251.0
9   Close_forcast  229.0
10   S_Close(t-1)  221.0
11            MA5  216.0
12    S_Open(t-1)  202.0
13   S_Close(t-2)  192.0
14           MA10  181.0
15   S_Close(t-3)  173.0
16   S_Close(t-5)  162.0
17           MA20  152.0
18     Lower_Band  138.0
19     Upper_Band  135.0
20           MA50  123.0
21          MA200   94.0
22      QQQ_Close   85.0
23       QQQ(t-1)   77.0
24       QQQ(t-2)   72.0
25       QQQ_MA10   71.0
26      SnP_Close   64.0
27       QQQ_MA20   59.0
28       QQQ(t-5)   58.0
29      SnP(t-1))   55.0
30     DJIA_Close   48.0
31       QQQ_MA50   47.0
32       SnP(t-5)   44.0
33     DJIA(t-1))   41.0
34      DJIA(t-5)   32.0
35            ATR   13.0
36           Year   13.0
37           SD20    4.0
38       MACD_EMA    3.0
39           MACD    2.0

In [14]:
aapl.columns

Index(['Date', 'Open', 'High', 'Low', 'Close(t)', 'Volume', 'SD20',
       'Upper_Band', 'Lower_Band', 'S_Close(t-1)', 'S_Close(t-2)',
       'S_Close(t-3)', 'S_Close(t-5)', 'S_Open(t-1)', 'MA5', 'MA10', 'MA20',
       'MA50', 'MA200', 'EMA10', 'EMA20', 'EMA50', 'EMA100', 'EMA200', 'MACD',
       'MACD_EMA', 'ATR', 'ADX', 'CCI', 'ROC', 'RSI', 'William%R', 'SO%K',
       'STD5', 'ForceIndex1', 'ForceIndex20', 'Date_col', 'Day', 'DayofWeek',
       'DayofYear', 'Week', 'Is_month_end', 'Is_month_start', 'Is_quarter_end',
       'Is_quarter_start', 'Is_year_end', 'Is_year_start', 'Is_leap_year',
       'Year', 'Month', 'QQQ_Close', 'QQQ(t-1)', 'QQQ(t-2)', 'QQQ(t-5)',
       'QQQ_MA10', 'QQQ_MA20', 'QQQ_MA50', 'SnP_Close', 'SnP(t-1))',
       'SnP(t-5)', 'DJIA_Close', 'DJIA(t-1))', 'DJIA(t-5)', 'Close_forcast',
       'stock'],
      dtype='object')

In [ ]:
    def obv(self):
        self.df['OBV'] = np.nan
        self.df.update({'OBV':[
            self.df.at[i, 'Volume'] if i == 0 else self.df.at[i - 1, 'OBV'] +
            self.df.at[i, 'Volume'] if self.df.at[i, 'Close'] >
            self.df.at[i - 1, 'Close'] else self.df.at[i - 1, 'OBV'] -
            self.df.at[i, 'Volume'] if self.df.at[i, 'Close'] < self.df.at[
                i - 1, 'Close'] else self.df.at[i - 1, 'OBV']
            for i in range(len(self.df))
        ]})

In [ ]:
None
        for i in range(len(self.df)):
            if i == 0:
                self.df.at[i, 'OBV'] = self.df.at[i, 'Volume']

            elif self.df.at[i, 'Close'] > self.df.at[i - 1, 'Close']:
                self.df.at[i,
                           'OBV'] = self.df.at[i - 1,
                                               'OBV'] + self.df.at[i, 'Volume']

            elif self.df.at[i, 'Close'] < self.df.at[i - 1, 'Close']:
                self.df.at[i,
                           'OBV'] = self.df.at[i - 1,
                                               'OBV'] - self.df.at[i, 'Volume']
            else:
                self.df.at[i, 'OBV'] = self.df.at[i - 1, 'OBV']

In [ ]:
class DataFrames():

    def __init__(self, ticker, year_start, month_start, day_start, indicators):

        self.ticker = ticker
        self.year_start = year_start
        self.month_start = month_start
        self.day_start = day_start
        self.import_()
        if indicators:
            self.daily_return()
            self.sd()
            self.moving_avg()
            self.exp_moving_avg()
            self.on_balance_volume()
            self.bollinger_bands()
            self.relative_strength_index()

    def import_(self):
        self.df = pdr.get_data_yahoo(
            self.ticker,
            dt.datetime(self.year_start, self.month_start, self.day_start),
            dt.datetime.now())
        self.df.reset_index(inplace=True)

    def daily_return(self):
        self.df['Return'] = self.df['Close'] - self.df['Open']

    def sd(self):
        self.df['SD'] = self.df['Return'].rolling(window=20,
                                                  min_periods=0).std()

    def moving_avg(self):
        self.df['MA20'] = self.df['Close'].rolling(window=20,
                                                   min_periods=0).mean()

    def exp_moving_avg(self):
        self.df['EMA20'] = self.df['Close'].ewm(span=20, adjust=False).mean()

    def on_balance_volume(self):
        self.df['OBV'] = np.where(
            self.df['Close'] > self.df['Close'].shift(1), self.df['Volume'],
            np.where(self.df['Close'] < self.df['Close'].shift(1),
                     -self.df['Volume'], 0)).cumsum()

    def bollinger_bands(self):
        self.df['BB_upper'] = self.df['MA20'] + self.df['SD'] * 2
        self.df['BB_lower'] = self.df['MA20'] - self.df['SD'] * 2
        
    def relative_strength_index(self):
        self.df['RSI'] = pta.rsi(self.df['Close'], length = 14)

In [40]:
import datetime
import pandas as pd
import numpy as np
import pandas_datareader.data as web 


class Security:
    def __init__(self, ticker, data_platform, start_date, end_date):
        self.ticker = ticker
        self.data_platform = data_platform
        self.start_date = start_date
        self.end_date = end_date
        self.df = None

    def fetch_stock_data(self):
        self.df = web.DataReader(self.ticker, self.data_platform, self.start_date, self.end_date)
        return self.df

In [41]:
class Evaluation:

    def __init__(self, security):
        self.security = security

    def simple_moving_average(self, period):
        df = self.security
        return df['Adj Close'].rolling(period).mean()

    def exp_moving_average(self, period):
        df = self.security
        return df['Adj Close'].ewm(span=period).mean()

    def rsi(self, period):
        df = self.security
        delta = df['Adj Close'].diff()
        up = delta * 0
        down = up.copy()
        up[delta > 0] = delta[delta > 0]
        down[delta < 0] = -delta[delta < 0]
        up[up.index[period - 1]] = np.mean(up[:period])
        up = up.drop(up.index[:(period - 1)])
        down[down.index[period - 1]] = np.mean(down[:period])
        down = down.drop(down.index[:(period - 1)])
        rs = up.ewm(span=period - 1).mean() / down.ewm(span=period - 1).mean()
        return 100 - 100 / (1 + rs)

In [42]:
start = datetime.datetime(2019, 1, 1)
end = datetime.datetime(2019, 4, 17)

s = Security('aapl', 'yahoo', start, end)
s = s.fetch_stock_data()

In [43]:
s

                 High        Low       Open      Close       Volume  Adj Close
Date
2019-01-02  39.712502  38.557499  38.722500  39.480000  148158800.0  38.105137
2019-01-03  36.430000  35.500000  35.994999  35.547501  365248800.0  34.309582
2019-01-04  37.137501  35.950001  36.132500  37.064999  234428400.0  35.774239
2019-01-07  37.207500  36.474998  37.174999  36.982498  219111200.0  35.694618
2019-01-08  37.955002  37.130001  37.389999  37.687500  164101200.0  36.375057
...               ...        ...        ...        ...          ...        ...
2019-04-11  50.250000  49.610001  50.212502  49.737499   83603200.0  48.211315
2019-04-12  50.035000  49.052502  49.799999  49.717499  111042800.0  48.191929
2019-04-15  49.962502  49.502499  49.645000  49.807499   70146400.0  48.279160
2019-04-16  50.342499  49.639999  49.865002  49.812500  102785600.0  48.284012
2019-04-17  50.845001  49.652500  49.884998  50.782501  115627200.0  49.224251

[74 rows x 6 columns]

In [44]:
e = Evaluation(security=s)

In [49]:
e.simple_moving_average(10)

Date
2019-01-02          NaN
2019-01-03          NaN
2019-01-04          NaN
2019-01-07          NaN
2019-01-08          NaN
                ...
2019-04-11    47.555088
2019-04-12    47.771246
2019-04-15    47.964865
2019-04-16    48.091603
2019-04-17    48.280135
Name: Adj Close, Length: 74, dtype: float64

In [ ]:
def train_val_test(df, train, validation):

    features = np.array(
        df[['High', 'Low', 'Open', 'Return', 'SD', 'MA20', 'EMA20', 'RSI']])
    target = np.array(df['Close'])

    data_len = df.shape[0]
    print(f'Length of data = {data_len}')

    train_split = int(data_len * train)
    print(f'Lenght of training set = {train_split}')

    val_split = train_split + int(data_len * validation)
    print(f'Length of validation set = {int(data_len * validation)}')

    print(
        f'Length of test set = {data_len - train_split - int(data_len * validation)}'
    )

    x_train, x_val, x_test = features[:train_split], features[
        train_split:val_split], features[val_split:]
    y_train, y_val, y_test = target[:train_split], target[
        train_split:val_split], target[val_split:]

    return x_train, x_val, x_test, y_train, y_val, y_test